### PR TITLE
Bud support

### PR DESCRIPTION
**Pull request by edsadr**
Bud has a custom proxyline not being supported right now:

```'BUD {"family":"TCP4","bud":{"host":"...","port":...},"peer":{...}'```

This PR implements support for it, and also adds a proper package.json with the same info

### CODE REVIEW

**Comment by tellnes** [comment]
Hi, this is great, but why it is needed? Bud supports the proxyline currently supported by this module.

**Comment by edsadr** [comment]
Well is needed if you switch Bud's proxyline options from `true` to `JSON` then the proxyline format changes and using the module will get `socket.proxyline` undefined

**Comment by tellnes** [comment]
But will switching that option give you any more information?

Over to your implementation. I think it would be better to implement this by detecting it early and provide to different branches in the code instead of a lots of ifs like you are doing right now.

**Comment by edsadr** [comment]
It is way different if you switch to JSON, it provides more info, the From Bud's docs:

```
if true - HAProxy compatible proxyline will be sent:
"PROXY TCP4 ... ... ... ..."
if "json":
'BUD {"family":"TCP4","bud":{"host":"...","port":...},"peer":{...}'
```

As you see even the `PROXY` is not included, about changing the implementation possible but just willing to do it if you truly think is something that you would like to add to your module

**Comment by tellnes** [comment]
If it give more information (which you just said it does), then I'm willing to merge something :)

I propose that you add a new case in the state switch and changes the `state` variable to use strings (eg. `START`, `PROXY` and `BUD`). I would probably have implemented it a bit different today (with functions instead of a switch), but this is my proposal to not rewrite the whole module.

Also, I think the module should parse the JSON from bud before finishing.

If you don't want to work on this anymore I'll probably implement it myself sometime in the future.

**Comment by edsadr** [comment]
I will take care over the weekend :)

**Pull request closed without merging**
